### ISSUE TITLE
Update Fails

### ISSUE THREAD

**Issue by Fyb3roptik** [aws-samples/appsync-with-postgraphile-rds#22]
Get this when running `npm run update`

```
➜  appsync-with-postgraphile git:(main) ✗ AWS_PROFILE=xxxx npm run update

> appsync-with-postgraphile-rds@0.1.0 update
> node ./scripts/update.js

Preparing Direct Lambda Resolver and AppSync API
{
  StatusCode: 200,
  FunctionError: 'Unhandled',
  ExecutedVersion: '$LATEST',
  Payload: `{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'graphql'\\nRequire stack:\\n- /var/task/index.js\\n- /var/runtime/UserFunction.js\\n- /var/runtime/Runtime.js\\n- /var/runtime/index.js","trace":["Runtime.ImportModuleError: Error: Cannot find module 'graphql'","Require stack:","- /var/task/index.js","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}`
}
```

**Comment by Fyb3roptik** [comment]
Ok I see my issue was running npm install inside of one of the folders instead of running npm install in root folder. Doing that fixed it for me but now I am getting timing out errors when running update

**Comment by Fyb3roptik** [comment]
Its an issue with permissions
